name: Release package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
          node-version-file: '.node-version'
          scope: '@dxopslab'
          cache: 'npm'
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
